const nativeFetch=globalThis.fetch.bind(globalThis);
globalThis.fetch=async(input,init={})=>{
 const url=String(input);if(!url.includes('generativelanguage.googleapis.com'))return nativeFetch(input,init);
 const request=JSON.parse(init.body||'{}');
 if(!url.includes('/models/gemma-4-26b-a4b-it:generateContent'))throw new Error('unexpected Gemma model endpoint');
 const config=request.generationConfig||{};
 if(config.responseMimeType!=='application/json'||config.responseSchema!==undefined||config.temperature!==0.2||config.maxOutputTokens!==8192)throw new Error('expected Gemma JSON MIME candidate request without unsupported response schema');
 const prompt=request.contents?.[0]?.parts?.[0]?.text||'';
 const selectedMatch=prompt.match(/SELECTED PANTRY INGREDIENTS[^\n]*:\n(\[[\s\S]*?\])\n\nAVAILABLE KITCHEN STAPLES/);
 const selected=selectedMatch?JSON.parse(selectedMatch[1]):[{name:'tomatoes'},{name:'cheese'}];
 const stapleMatch=prompt.match(/AVAILABLE KITCHEN STAPLES[^\n]*:\n(\[[\s\S]*?\])\n\nUSER PREFERENCES/);
 const staples=stapleMatch?JSON.parse(stapleMatch[1]):[];
 const equipment=(prompt.match(/Available equipment\/methods[^:]*: ([^\n]+)/i)||[])[1]||'One pan';
 const eq=equipment.toLowerCase(), names=selected.map(i=>i.name), find=re=>selected.find(i=>re.test(i.name.toLowerCase()));
 const tomato=find(/tomato/), paneer=find(/paneer/), spinach=find(/spinach/), eggs=find(/egg/), cheese=find(/cheese/), pancake=find(/pancake mix/);
 const ingredients=selected.map(i=>({name:i.name,amount:i.quantity==null?(/paneer|tofu|cheese/i.test(i.name)?'150 g':/egg/i.test(i.name)?'2':/curd|yogurt/i.test(i.name)?'1 cup':'as available'):String(i.quantity),source:'selected'}));
 const addStaple=(name,amount)=>{if(staples.some(s=>s.toLowerCase()===name.toLowerCase()))ingredients.push({name,amount,source:'kitchen_staple'});};
 let title='Selected Pantry Bowl',steps=['Combine the selected ingredients and serve.'],eqList=['stovetop','pan'];
 if(eq.includes('microwave')){eqList=['microwave','microwave-safe dish'];steps=['Place the selected ingredients in a microwave-safe dish.','Microwave on HIGH for 60 seconds, stir, then microwave for 30 seconds more.'];}
 else if(eq.includes('oven')){eqList=['oven','oven-safe dish'];steps=['Heat the oven to 190°C and place the ingredients in an oven-safe dish.','Bake for 12 minutes, until hot and cooked through.'];}
 else if(eq.includes('air fryer')){eqList=['air fryer'];steps=['Place the ingredients in the air fryer basket.','Air fry at 180°C for 8 minutes, then check they are hot throughout.'];}
 else if(eq.includes('no-cook')){eqList=['no-cook'];steps=['Slice and arrange the selected ingredients.','Serve without heating.'];}
 else if(eq.includes('one pan')){eqList=['one pan'];steps=['Add the selected ingredients directly to the same pan.','Cook them together in that pan until ready.'];}
 else if(eq.includes('one pot')){eqList=['one pot'];steps=['Add the selected ingredients to the same pot.','Cook gently in the pot until ready.'];}
 else eqList=['stovetop','pan'];
 if(tomato&&paneer){title=eq.includes('microwave')?'Microwave Paneer Tomato Masala':'Quick Paneer Tomato Masala';if(eq.includes('microwave')){addStaple('turmeric','1/4 tsp');steps=['Dice the selected tomatoes and paneer into a microwave-safe dish.','Add the available turmeric, cover loosely, and microwave for 90 seconds.','Stir gently and microwave for 30 seconds more until hot.'];}else{addStaple('cumin seeds','1/2 tsp');addStaple('turmeric','1/4 tsp');addStaple('red chilli powder','1/4 tsp');steps=['Heat a pan on the stovetop and let the available cumin seeds sizzle briefly.','Add chopped selected tomatoes with turmeric and red chilli powder; cook until soft.','Fold in the paneer and simmer briefly until coated and hot.'];}}
 else if(eggs&&tomato){title='Tomato Egg Bhurji';addStaple('cumin seeds','1/2 tsp');steps=['Heat a pan on the stovetop and briefly sizzle the cumin seeds.','Add chopped tomatoes and cook until softened.','Pour in the eggs and stir on low heat until just set.'];}
 else if(paneer&&spinach){title='Spinach Paneer';addStaple('cumin seeds','1/2 tsp');addStaple('garam masala','1/4 tsp');steps=['Heat a pan on the stovetop and briefly sizzle the cumin seeds.','Add the spinach and stir until wilted.','Fold in paneer and garam masala; cook gently until hot.'];}
 else if(pancake){title='Microwave Pancake Mug';eqList=['microwave','microwave-safe mug'];steps=['Stir the pancake mix with the listed amount of water in a microwave-safe mug.','Microwave on HIGH for 60 seconds.','Check that the center is set; continue in 10-second bursts if needed.'];}
 else if(tomato&&cheese){if(eq.includes('no-cook')){title='No-Cook Tomato Cheese Bites';steps=['Slice the tomatoes and cheese.','Layer the selected slices together.','Serve without heating.'];}else if(eq.includes('one pan')){title='One-Pan Tomato Cheese Melt';eqList=['one pan'];steps=['Slice the tomatoes and add them directly to the same pan.','Cook the tomatoes in that pan until juicy.','Add cheese to the same pan and cover until softened.'];}else{title=eq.includes('microwave')?'Microwave Tomato Cheese Melt':'Stovetop Tomato Cheese';if(eq.includes('microwave')){eqList=['microwave','microwave-safe dish'];steps=['Slice tomatoes into a microwave-safe dish and microwave for 60 seconds.','Top with cheese and microwave for 30 seconds.','Check that the cheese has melted; continue in short bursts if needed.'];}else steps=['Warm a pan on the stovetop and cook the sliced tomatoes until juicy.','Add the cheese over the tomatoes and cover the same pan.','Cook gently until the cheese softens and the tomatoes are hot.'];}}
 const allText=steps.join(' ').toLowerCase();
 for(const staple of staples){const s=staple.toLowerCase();if(allText.includes(s)&&!ingredients.some(i=>i.name.toLowerCase()===s))addStaple(staple,'to taste');}
 const recipe={title,description:`A ${eq.includes('microwave')?'microwave':'stovetop'} recipe built around ${names.join(' and ')}.`,cuisine:(prompt.match(/Cuisine: ([^.\n]+)/)||[])[1]||'Everyday',servings:1,timeMinutes:Math.min(12,Number((prompt.match(/TIME: (\d+)/)||[])[1]||20)),equipment:eqList,ingredients,steps,substitutions:[],tips:[]};
 let result=recipe;
 if(prompt.includes('Goal: validation-case')&&!prompt.includes('semantic constraint failure'))result={...recipe,equipment:['Oven'],steps:['Place everything in an oven-safe dish.','Bake in the oven until tender.']};
 if(prompt.includes('Goal: fallback-case'))return new Response(JSON.stringify({error:{message:'mock provider unavailable'}}),{status:503,headers:{'content-type':'application/json'}});
 const requested=Number((prompt.match(/Generate exactly (\d+)/)||[])[1]||8),limit=Number((prompt.match(/Maximum cooking time: (\d+)/)||[])[1]||60),multi=/stovetop[^\n]*microwave|microwave[^\n]*stovetop/i.test(equipment);
 const variants=Array.from({length:requested},(_,index)=>{
  const chosen=multi?(index%2===1?'microwave':'stovetop'):eq.includes('microwave')?'microwave':eq.includes('no-cook')?'no-cook':eq.includes('oven')?'oven':eq.includes('air fryer')?'air fryer':eq.includes('stovetop')?'stovetop':eq.includes('one pot')?'one-pot':'one-pan';
  let equipmentList=chosen==='microwave'?['microwave-safe dish']:chosen==='no-cook'?['no-cook']:chosen==='oven'?['oven','oven-safe dish']:chosen==='air fryer'?['air fryer']:chosen==='one-pan'?['one-pan']:['stovetop','pan'];
  let steps=chosen==='microwave'?['Place the selected ingredients in a microwave-safe dish.','Microwave on HIGH for 60 seconds, stir, then microwave for 30 seconds more.']:chosen==='no-cook'?['Slice and arrange the selected ingredients.','Serve without heating.']:chosen==='oven'?['Place the selected ingredients in an oven-safe dish.','Bake in the oven at 190°C until hot and tender.']:chosen==='air fryer'?['Place the selected ingredients in the air fryer basket.','Air fry at 180°C until hot and tender.']:chosen==='one-pan'?['Add the selected ingredients directly to the same pan.','Cook everything together in that pan until ready.']:['Heat a pan on the stovetop.','Cook the selected ingredients in the pan until ready.'];
  if(tomato&&paneer){if(chosen==='microwave'){title= 'Microwave Paneer Tomato Masala';steps=['Dice the selected tomatoes and paneer into a microwave-safe dish.','Add the available turmeric, cover loosely, and microwave for 90 seconds.','Stir gently and microwave for 30 seconds more until hot.'];addStaple('turmeric','1/4 tsp');}else{title='Quick Paneer Tomato Masala';steps=['Heat a pan on the stovetop and let the available cumin seeds sizzle briefly.','Add chopped selected tomatoes with turmeric and red chilli powder; cook until soft.','Fold in the paneer and simmer briefly until coated and hot.'];addStaple('cumin seeds','1/2 tsp');addStaple('turmeric','1/4 tsp');addStaple('red chilli powder','1/4 tsp');}}
  if(eggs&&tomato){title=chosen==='microwave'?'Microwave Tomato Eggs':'Tomato Egg Bhurji';steps=chosen==='microwave'?['Place the selected eggs and tomatoes in a microwave-safe dish.','Microwave for 30 seconds, stir, and microwave until the eggs set.']:['Heat a pan on the stovetop and briefly sizzle the cumin seeds.','Add chopped tomatoes and cook until softened.','Pour in the eggs and stir on low heat until just set.'];addStaple('cumin seeds','1/2 tsp');}
  if(paneer&&spinach){title=chosen==='microwave'?'Microwave Spinach Paneer':'Spinach Paneer';steps=chosen==='microwave'?['Put the selected spinach in a microwave-safe container and microwave on HIGH for 60 seconds.','Stir in paneer, cover loosely, and microwave for 45 seconds more.']:['Heat a pan on the stovetop and briefly sizzle the cumin seeds.','Add spinach and stir until wilted.','Fold in paneer and garam masala; cook gently until hot.'];addStaple('cumin seeds','1/2 tsp');}
  if(pancake){title=chosen==='microwave'?'Microwave Pancake Mug':'Stovetop Pancake';equipmentList=chosen==='microwave'?['microwave-safe mug']:['stovetop','pan'];steps=chosen==='microwave'?['Stir the pancake mix with water in a microwave-safe mug.','Microwave on HIGH for 60 seconds.','Check the center and heat in short bursts until set.']:['Stir the pancake mix with water in a bowl.','Pour into a warm pan and cook until bubbles appear.','Turn and cook until set.'];}
  const variantSteps=steps.map((step,i)=>index?`${step} (candidate ${index+1}; ${['crisp-edged','gently simmered','soft-centered','lightly browned'][index%4]} preparation)` :step);
  const usedStaples=staples.filter(name=>variantSteps.join(' ').toLowerCase().includes(name.toLowerCase())).map(name=>({name,amount:'1 tsp',source:'kitchen_staple'}));const ingredients=[...recipe.ingredients.filter(i=>i.source==='selected'),...usedStaples].map(i=>({...i}));
  if(names.includes('pyaaj')&&names.includes('besan'))for(const ingredient of ingredients.filter(i=>i.source==='selected'))ingredient.source=ingredient.name==='pyaaj'?'pyaaj':'pantry';
  if(names.includes('spinach')&&names.includes('mushroom'))for(const ingredient of ingredients.filter(i=>i.source==='selected'))ingredient.source=ingredient.name;
  return {...recipe,title:index?`${title} · ${['Tender','Golden','Quick','Rustic','Bright','Savory','Simple'][index%7]}`:title,equipment:equipmentList,ingredients,steps:variantSteps,timeMinutes:Math.max(1,Math.min(limit,Math.min(60,5+index*2))),description:`${recipe.description} Variation ${index+1}.`};
 });
 if(prompt.includes('Goal: partial-candidates'))variants[0]={...variants[0],ingredients:[...variants[0].ingredients,{name:'unavailable onion',amount:'1',source:'selected'}]};
 if(prompt.includes('Goal: all-invalid-case'))variants.forEach(v=>{v.ingredients=[...v.ingredients,{name:'unavailable onion',amount:'1',source:'selected'}]});
 const raw=prompt.includes('Goal: truncated-case')?`[${JSON.stringify(variants[0])},${JSON.stringify(variants[1])},{"title":"cut off"`:`Model diagnostic wrapper\n${JSON.stringify(variants)}\nEnd.`;
 return new Response(JSON.stringify({candidates:[{content:{parts:[{thought:true,text:'not the recipes'},{text:raw}]}}]}),{status:200,headers:{'content-type':'application/json'}});
};
